#ifndef _CONSTANTS_H
#define _CONSTANTS_H

enum AxisType
{
	X_AXIS = 0,
	Y_AXIS,
	Z_AXIS
};


#define APPLICATION_WINDOW_HEIGHT 1080
#define APPLICATION_WINDOW_WIDTH 1920


#define CANVAS_LEFT 10
#define CANVAS_RIGHT APPLICATION_WINDOW_WIDTH / 1.15
#define CANVAS_BOTTOM 10
#define CANVAS_TOP APPLICATION_WINDOW_HEIGHT / 1.15

#define COLOR_PANEL_LEFT CANVAS_RIGHT + 5
#define COLOR_PANEL_RIGHT COLOR_PANEL_LEFT + 90
#define COLOR_PANEL_TOP CANVAS_TOP
#define COLOR_PANEL_BOTTOM CANVAS_BOTTOM

#define TOOLBAR_LEFT CANVAS_LEFT
#define TOOLBAR_RIGHT COLOR_PANEL_RIGHT
#define TOOLBAR_BOTTOM CANVAS_TOP + 10
#define TOOLBAR_TOP TOOLBAR_BOTTOM + 70

#define MENUBAR_LEFT CANVAS_LEFT
#define MENUBAR_RIGHT COLOR_PANEL_RIGHT
#define MENUBAR_TOP APPLICATION_WINDOW_HEIGHT
#define MENUBAR_BOTTOM TOOLBAR_TOP

#define GAP 4
#define COLOR_SQUARE_SIDE 30

#endif