#ifndef _CONSTANTS_H
#define _CONSTANTS_H
#define DEBUG 0
#if DEBUG
#define LOG(s) cout<<s<<endl;
#else
#define LOG(s) 
#endif
enum AxisType
{
	X_AXIS = 0,
	Y_AXIS,
	Z_AXIS
};
enum MenuOps
{
	NEW = 1,
	OPEN,
	SAVE,
	EXIT,
	CUT_PASTE,
	COPY_PASTE
};
enum ColorType
{
	BLACK,
	RED,
	GREEN,
	BLUE,
	CYAN,
	MAGENTA,
	YELLOW,
	WHITE
};


#define APPLICATION_WINDOW_HEIGHT 800
#define APPLICATION_WINDOW_WIDTH 800
#define MULT_FACTOR 3
#define NAMSIZE 25

#define CANVAS_LEFT 10
#define CANVAS_RIGHT APPLICATION_WINDOW_WIDTH / 1.15
#define CANVAS_BOTTOM 10
#define CANVAS_TOP APPLICATION_WINDOW_HEIGHT / 1.15

#define COLOR_PANEL_LEFT CANVAS_RIGHT + 10
#define COLOR_PANEL_RIGHT COLOR_PANEL_LEFT + 90
#define COLOR_PANEL_TOP CANVAS_TOP
#define COLOR_PANEL_BOTTOM CANVAS_BOTTOM

#define TOOLBAR_LEFT CANVAS_LEFT
#define TOOLBAR_RIGHT COLOR_PANEL_RIGHT
#define TOOLBAR_BOTTOM CANVAS_TOP + 10
#define TOOLBAR_TOP TOOLBAR_BOTTOM + 70

#define MENUBAR_LEFT CANVAS_LEFT
#define MENUBAR_RIGHT COLOR_PANEL_RIGHT
#define MENUBAR_TOP APPLICATION_WINDOW_HEIGHT
#define MENUBAR_BOTTOM TOOLBAR_TOP

#define GAP 4
#define TOOLBAR_NUM_ROWS 2
#define TOOLBAR_NUM_COLS 3
#define TOOL_BORDER_WIDTH 100
#define TOOL_BORDER_HEIGHT 30

#define COLOR_SQUARE_SIDE 30
#define COLOR_PANEL_NUM_ROWS 5
#define COLOR_PANEL_NUM_COLS 3

#define OP_NEW_X 20
#define OP_OPEN_X 60
#define OP_SAVE_X 100
#define OP_EXIT_X 140
#define OP_CUPASTE_X 170
#define OP_COPY_X 230
#endif